name: My build action requiring more space
on: push

jobs:
  build:
    name: Build my artifact
    runs-on: ubuntu-20.04
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: '6.0'
      - name: Build
        run: |
          echo "Free space:"
          df -h
          wget https://static.openfoodfacts.org/data/openfoodfacts-mongodbdump.tar.gz 2>/tmp/err.log || cat /tmp/err.log; rm /tmp/err.log
          mongorestore -host="127.0.0.1" --port="27017" --gzip --archive="openfoodfacts-mongodbdump.tar.gz"
          echo "Finished importing"
